// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/v1/fizzbuzz/fizzbuzz.proto

package fizzbuzzV1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetFizzBuzzRequest struct {
	FirstWord            string   `protobuf:"bytes,1,opt,name=first_word,json=firstWord,proto3" json:"first_word,omitempty"`
	SecondWord           string   `protobuf:"bytes,2,opt,name=second_word,json=secondWord,proto3" json:"second_word,omitempty"`
	FirstMultiple        int64    `protobuf:"varint,3,opt,name=first_multiple,json=firstMultiple,proto3" json:"first_multiple,omitempty"`
	SecondMultiple       int64    `protobuf:"varint,4,opt,name=second_multiple,json=secondMultiple,proto3" json:"second_multiple,omitempty"`
	Limit                int64    `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFizzBuzzRequest) Reset()         { *m = GetFizzBuzzRequest{} }
func (m *GetFizzBuzzRequest) String() string { return proto.CompactTextString(m) }
func (*GetFizzBuzzRequest) ProtoMessage()    {}
func (*GetFizzBuzzRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d73ebc6e13cd4d2, []int{0}
}

func (m *GetFizzBuzzRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFizzBuzzRequest.Unmarshal(m, b)
}
func (m *GetFizzBuzzRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFizzBuzzRequest.Marshal(b, m, deterministic)
}
func (m *GetFizzBuzzRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFizzBuzzRequest.Merge(m, src)
}
func (m *GetFizzBuzzRequest) XXX_Size() int {
	return xxx_messageInfo_GetFizzBuzzRequest.Size(m)
}
func (m *GetFizzBuzzRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFizzBuzzRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFizzBuzzRequest proto.InternalMessageInfo

func (m *GetFizzBuzzRequest) GetFirstWord() string {
	if m != nil {
		return m.FirstWord
	}
	return ""
}

func (m *GetFizzBuzzRequest) GetSecondWord() string {
	if m != nil {
		return m.SecondWord
	}
	return ""
}

func (m *GetFizzBuzzRequest) GetFirstMultiple() int64 {
	if m != nil {
		return m.FirstMultiple
	}
	return 0
}

func (m *GetFizzBuzzRequest) GetSecondMultiple() int64 {
	if m != nil {
		return m.SecondMultiple
	}
	return 0
}

func (m *GetFizzBuzzRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetFizzBuzzResponse struct {
	Fizzbuzzed           string   `protobuf:"bytes,1,opt,name=fizzbuzzed,proto3" json:"fizzbuzzed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFizzBuzzResponse) Reset()         { *m = GetFizzBuzzResponse{} }
func (m *GetFizzBuzzResponse) String() string { return proto.CompactTextString(m) }
func (*GetFizzBuzzResponse) ProtoMessage()    {}
func (*GetFizzBuzzResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d73ebc6e13cd4d2, []int{1}
}

func (m *GetFizzBuzzResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFizzBuzzResponse.Unmarshal(m, b)
}
func (m *GetFizzBuzzResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFizzBuzzResponse.Marshal(b, m, deterministic)
}
func (m *GetFizzBuzzResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFizzBuzzResponse.Merge(m, src)
}
func (m *GetFizzBuzzResponse) XXX_Size() int {
	return xxx_messageInfo_GetFizzBuzzResponse.Size(m)
}
func (m *GetFizzBuzzResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFizzBuzzResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFizzBuzzResponse proto.InternalMessageInfo

func (m *GetFizzBuzzResponse) GetFizzbuzzed() string {
	if m != nil {
		return m.Fizzbuzzed
	}
	return ""
}

func init() {
	proto.RegisterType((*GetFizzBuzzRequest)(nil), "fizzbuzz.v1.GetFizzBuzzRequest")
	proto.RegisterType((*GetFizzBuzzResponse)(nil), "fizzbuzz.v1.GetFizzBuzzResponse")
}

func init() { proto.RegisterFile("api/v1/fizzbuzz/fizzbuzz.proto", fileDescriptor_7d73ebc6e13cd4d2) }

var fileDescriptor_7d73ebc6e13cd4d2 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4b, 0x2c, 0xc8, 0xd4,
	0x2f, 0x33, 0xd4, 0x4f, 0xcb, 0xac, 0xaa, 0x4a, 0x2a, 0xad, 0xaa, 0x82, 0x33, 0xf4, 0x0a, 0x8a,
	0xf2, 0x4b, 0xf2, 0x85, 0xb8, 0xe1, 0xfc, 0x32, 0x43, 0x29, 0x99, 0xf4, 0xfc, 0xfc, 0xf4, 0x9c,
	0x54, 0x7d, 0x90, 0x9e, 0xc4, 0xbc, 0xbc, 0xfc, 0x92, 0xc4, 0x92, 0xcc, 0xfc, 0xbc, 0x62, 0x88,
	0x52, 0xa5, 0x5d, 0x8c, 0x5c, 0x42, 0xee, 0xa9, 0x25, 0x6e, 0x99, 0x55, 0x55, 0x4e, 0xa5, 0x55,
	0x55, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0xb2, 0x5c, 0x5c, 0x69, 0x99, 0x45, 0xc5,
	0x25, 0xf1, 0xe5, 0xf9, 0x45, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x9c, 0x60, 0x91,
	0xf0, 0xfc, 0xa2, 0x14, 0x21, 0x79, 0x2e, 0xee, 0xe2, 0xd4, 0xe4, 0xfc, 0xbc, 0x14, 0x88, 0x3c,
	0x13, 0x58, 0x9e, 0x0b, 0x22, 0x04, 0x56, 0xa0, 0xca, 0xc5, 0x07, 0xd1, 0x9f, 0x5b, 0x9a, 0x53,
	0x92, 0x59, 0x90, 0x93, 0x2a, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x1c, 0xc4, 0x0b, 0x16, 0xf5, 0x85,
	0x0a, 0x0a, 0xa9, 0x73, 0xf1, 0x43, 0xcd, 0x81, 0xab, 0x63, 0x01, 0xab, 0xe3, 0x83, 0x08, 0xc3,
	0x15, 0x8a, 0x70, 0xb1, 0xe6, 0x64, 0xe6, 0x66, 0x96, 0x48, 0xb0, 0x82, 0xa5, 0x21, 0x1c, 0x25,
	0x53, 0x2e, 0x61, 0x14, 0xb7, 0x17, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0xc9, 0x81, 0x1c, 0x0f,
	0x09, 0x80, 0x54, 0x98, 0xe3, 0x91, 0x44, 0x8c, 0x2e, 0x30, 0x72, 0xf1, 0xc3, 0x34, 0x05, 0xa7,
	0x16, 0x95, 0x65, 0x26, 0xa7, 0x0a, 0xed, 0x61, 0xe4, 0xe2, 0x46, 0x32, 0x4b, 0x48, 0x5e, 0x0f,
	0x29, 0x0c, 0xf5, 0x30, 0x43, 0x48, 0x4a, 0x01, 0xb7, 0x02, 0x88, 0x33, 0x94, 0xb2, 0x9a, 0x2e,
	0x3f, 0x99, 0xcc, 0x94, 0x22, 0xc4, 0x83, 0x1c, 0x55, 0x51, 0x21, 0x42, 0x41, 0x28, 0x51, 0x57,
	0x8d, 0x08, 0xe7, 0x5a, 0xfd, 0x6a, 0xa4, 0x50, 0xad, 0x85, 0x49, 0xc1, 0x82, 0x06, 0x21, 0x8d,
	0x24, 0x02, 0x0e, 0x88, 0x5a, 0x27, 0xa9, 0x28, 0xb8, 0x07, 0xc3, 0x0c, 0x57, 0x31, 0x71, 0xc3,
	0x1c, 0xa3, 0x17, 0x66, 0x98, 0xc4, 0x06, 0x8e, 0x69, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xd8, 0x75, 0x0b, 0xdf, 0x36, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FizzBuzzServiceClient is the client API for FizzBuzzService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FizzBuzzServiceClient interface {
	// GetFizzBuzz
	// this endpoint is based on the famous FizzBuzz test
	// if the parameters are ommited it will take default value as defined :
	// * defaultFirstWord  = "fizz"
	// * defaultSecondWord = "buzz"
	// * defaultLimit = 100
	//
	// the default value for first_multiple & second_multiple will be 0,
	// throwing an error as division by 0 is not well defined
	GetFizzBuzz(ctx context.Context, in *GetFizzBuzzRequest, opts ...grpc.CallOption) (*GetFizzBuzzResponse, error)
}

type fizzBuzzServiceClient struct {
	cc *grpc.ClientConn
}

func NewFizzBuzzServiceClient(cc *grpc.ClientConn) FizzBuzzServiceClient {
	return &fizzBuzzServiceClient{cc}
}

func (c *fizzBuzzServiceClient) GetFizzBuzz(ctx context.Context, in *GetFizzBuzzRequest, opts ...grpc.CallOption) (*GetFizzBuzzResponse, error) {
	out := new(GetFizzBuzzResponse)
	err := c.cc.Invoke(ctx, "/fizzbuzz.v1.FizzBuzzService/GetFizzBuzz", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FizzBuzzServiceServer is the server API for FizzBuzzService service.
type FizzBuzzServiceServer interface {
	// GetFizzBuzz
	// this endpoint is based on the famous FizzBuzz test
	// if the parameters are ommited it will take default value as defined :
	// * defaultFirstWord  = "fizz"
	// * defaultSecondWord = "buzz"
	// * defaultLimit = 100
	//
	// the default value for first_multiple & second_multiple will be 0,
	// throwing an error as division by 0 is not well defined
	GetFizzBuzz(context.Context, *GetFizzBuzzRequest) (*GetFizzBuzzResponse, error)
}

func RegisterFizzBuzzServiceServer(s *grpc.Server, srv FizzBuzzServiceServer) {
	s.RegisterService(&_FizzBuzzService_serviceDesc, srv)
}

func _FizzBuzzService_GetFizzBuzz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFizzBuzzRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FizzBuzzServiceServer).GetFizzBuzz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fizzbuzz.v1.FizzBuzzService/GetFizzBuzz",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FizzBuzzServiceServer).GetFizzBuzz(ctx, req.(*GetFizzBuzzRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FizzBuzzService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fizzbuzz.v1.FizzBuzzService",
	HandlerType: (*FizzBuzzServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFizzBuzz",
			Handler:    _FizzBuzzService_GetFizzBuzz_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/fizzbuzz/fizzbuzz.proto",
}
